backend:
  name: git-gateway
  repo: KarthikeyanSeenivasan/Black_irish
  branch: main
media_folder: "images/"

collections:
  - name: "home"
    label: "Home"

    create: true
    file: "content/home/home.json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "about"
    label: "About"

    create: true
    file: "content/about/about.json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "img", widget: "image" }
